/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as EueeRouteImport } from './routes/euee'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamsIndexRouteImport } from './routes/exams.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as ExamsSlugRouteImport } from './routes/exams.$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const EueeRoute = EueeRouteImport.update({
  id: '/euee',
  path: '/euee',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsIndexRoute = ExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsSlugRoute = ExamsSlugRouteImport.update({
  id: '/exams/$slug',
  path: '/exams/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/euee': typeof EueeRoute
  '/library': typeof LibraryRoute
  '/pricing': typeof PricingRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/exams/$slug': typeof ExamsSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/exams/': typeof ExamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/euee': typeof EueeRoute
  '/library': typeof LibraryRoute
  '/pricing': typeof PricingRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/exams/$slug': typeof ExamsSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/exams': typeof ExamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/euee': typeof EueeRoute
  '/library': typeof LibraryRoute
  '/pricing': typeof PricingRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/exams/$slug': typeof ExamsSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/exams/': typeof ExamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/books'
    | '/contact'
    | '/euee'
    | '/library'
    | '/pricing'
    | '/courses/$slug'
    | '/exams/$slug'
    | '/courses/'
    | '/exams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/books'
    | '/contact'
    | '/euee'
    | '/library'
    | '/pricing'
    | '/courses/$slug'
    | '/exams/$slug'
    | '/courses'
    | '/exams'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/books'
    | '/contact'
    | '/euee'
    | '/library'
    | '/pricing'
    | '/courses/$slug'
    | '/exams/$slug'
    | '/courses/'
    | '/exams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BooksRoute: typeof BooksRoute
  ContactRoute: typeof ContactRoute
  EueeRoute: typeof EueeRoute
  LibraryRoute: typeof LibraryRoute
  PricingRoute: typeof PricingRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  ExamsSlugRoute: typeof ExamsSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ExamsIndexRoute: typeof ExamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/euee': {
      id: '/euee'
      path: '/euee'
      fullPath: '/euee'
      preLoaderRoute: typeof EueeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/': {
      id: '/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof ExamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$slug': {
      id: '/exams/$slug'
      path: '/exams/$slug'
      fullPath: '/exams/$slug'
      preLoaderRoute: typeof ExamsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BooksRoute: BooksRoute,
  ContactRoute: ContactRoute,
  EueeRoute: EueeRoute,
  LibraryRoute: LibraryRoute,
  PricingRoute: PricingRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  ExamsSlugRoute: ExamsSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ExamsIndexRoute: ExamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
